<img src="https://drive.google.com/uc?export=view&id=1Y-EIpLOigI9ycCOZRrRSFzAfuN9cxhqT" alt="Hobot Academy" width="300" height="300">

<h1 align="center"><font size="14">Hands-On Machine Learning</font></h1>
<h3 align="center"><font size="7">Session03: Numpy | Part01</font></h3>
<h3 align="center">Zahra Amini</h3>

In [1]:
# pip install pip --upgrade

In [2]:
# pip install numpy

In [3]:
import numpy as np
print(np.__version__)

1.21.5


In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

# 🟣 Zeros, Ones

In [7]:
a = np.zeros((3, 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 🟣 Arange Numbers

In [12]:
a = np.arange(15)

In [16]:
a = a.reshape(3, 5)

In [15]:
# a.reshape(10, 5)

In [17]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
a.shape

(3, 5)

In [19]:
a.dtype

dtype('int32')

In [21]:
b = np.array([2.2, 3, 0.5])
b.dtype.name

'float64'

In [22]:
np.array([[2, 3, 4.5],[1, 6.5, 9]])

array([[2. , 3. , 4.5],
       [1. , 6.5, 9. ]])

# 🟣 Random Numbers

In [24]:
np.random.rand(2, 3)

array([[0.0907529 , 0.05845777, 0.72876007],
       [0.85178779, 0.30034605, 0.73249534]])

In [27]:
a = np.arange(10, 50, 5)

In [28]:
a

array([10, 15, 20, 25, 30, 35, 40, 45])

In [29]:
np.linspace(0, 2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

# 🟣 Adding, removing, and sorting elements

In [30]:
a = np.array([1, 2, 3, 5, 8])
a

array([1, 2, 3, 5, 8])

In [38]:
a = np.append(a, 10)
a

array([ 1,  2,  3,  5,  8, 10, 10])

In [35]:
index = 3
np.delete(a, index)

array([ 1,  2,  3,  8, 10])

In [36]:
np.sort(a)

array([ 1,  2,  3,  5,  8, 10])

In [37]:
b = np.array([5, 8,0,2, 7])
np.sort(b)

array([0, 2, 5, 7, 8])

### concatenate

In [39]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [40]:
a

array([1, 2, 3, 4])

In [41]:
b

array([5, 6, 7, 8])

In [42]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### ndarray.ndim, ndarray.size, ndarray.shape

In [43]:
a = np.array([1, 2, 3, 4])
a.ndim

1

In [44]:
a.size

4

In [47]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(4,)
1
4
int32


In [52]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
a = a.reshape(2, 5, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [50]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(2, 5, 2)
3
20
int32


In [55]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 🟣 reshape an array

In [56]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [57]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [59]:
np.arange(6).reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# 🟣 Array Operations

In [60]:
a = np.array([10, 20, 30 , 40])

b = np.array([1, 2, 3, 4])

In [61]:
a

array([10, 20, 30, 40])

In [62]:
b

array([1, 2, 3, 4])

In [63]:
a - b

array([ 9, 18, 27, 36])

In [64]:
a + b

array([11, 22, 33, 44])

In [65]:
a * b

array([ 10,  40,  90, 160])

In [66]:
a @ b

300

In [73]:
A = np.array([[1, 2, -3],
             [0, 4, 2]])

A

array([[ 1,  2, -3],
       [ 0,  4,  2]])

In [74]:
B = np.array([[4,5],
             [1, -1],
             [2, 3]])

B

array([[ 4,  5],
       [ 1, -1],
       [ 2,  3]])

In [75]:
A @ B

array([[ 0, -6],
       [ 8,  2]])

In [76]:
np.dot(A, B)

array([[ 0, -6],
       [ 8,  2]])

In [77]:
np.dot(B, A)

array([[ 4, 28, -2],
       [ 1, -2, -5],
       [ 2, 16,  0]])

### sum, max, min, mean

In [78]:
c = np.array([1, 2, 3, 4, 5])

In [79]:
c

array([1, 2, 3, 4, 5])

In [80]:
c.sum()

15

In [81]:
c.max()

5

In [82]:
c.min()

1

In [83]:
c.mean()

3.0

# 🟣 Broadcasting

In [84]:
d = np.array([[1], [2]])
d

array([[1],
       [2]])

In [85]:
d * 1.5

array([[1.5],
       [3. ]])

### unique()

In [86]:
a = np.array([[1, 2, 3, 6],
             [1, 6, 9, 12],
             [2, 2, 4, 4]])
a

array([[ 1,  2,  3,  6],
       [ 1,  6,  9, 12],
       [ 2,  2,  4,  4]])

In [87]:
np.unique(a)

array([ 1,  2,  3,  4,  6,  9, 12])

# 🟣 Boolean Indexing

In [88]:
a

array([[ 1,  2,  3,  6],
       [ 1,  6,  9, 12],
       [ 2,  2,  4,  4]])

In [89]:
a[1,1]

6

In [90]:
print(a>5)

[[False False False  True]
 [False  True  True  True]
 [False False False False]]


In [91]:
a[a>5]

array([ 6,  6,  9, 12])

# 🟣 Slicing

In [92]:
a

array([[ 1,  2,  3,  6],
       [ 1,  6,  9, 12],
       [ 2,  2,  4,  4]])

In [94]:
b = np.array([1, 2, 3, 4, 5])
b

array([1, 2, 3, 4, 5])

In [95]:
b[:3]

array([1, 2, 3])

In [96]:
b[2:4]

array([3, 4])

In [97]:
a 

array([[ 1,  2,  3,  6],
       [ 1,  6,  9, 12],
       [ 2,  2,  4,  4]])

In [99]:
a[1:2]

array([[ 1,  6,  9, 12]])

In [100]:
a[:2, 1:3]

array([[2, 3],
       [6, 9]])

In [101]:
a[(a>2) & (a<8)]

array([3, 6, 6, 4, 4])

# 🟣 Transposing a matrix

In [102]:
a = np.array([[1, 3, 5],
             [2, 4, 6]])

a

array([[1, 3, 5],
       [2, 4, 6]])

In [103]:
a.shape

(2, 3)

In [104]:
a_t = a.T
a_t

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
a_t.shape

(3, 2)

### reverse an array ---> np.flip()

In [106]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [107]:
np.flip(a)

array([5, 4, 3, 2, 1])

### flattening

In [109]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])

In [110]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

# Finished!