<img src="https://drive.google.com/uc?export=view&id=1Y-EIpLOigI9ycCOZRrRSFzAfuN9cxhqT" alt="Hobot Academy" width="300" height="300">

<h1 align="center"><font size="14">Hands-On Machine Learning</font></h1>
<h3 align="center"><font size="7">Session08: Polynomial Regression</font></h3>
<h3 align="center">Zahra Amini</h3>

In [1]:
import numpy as np

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
X = np.array([[0],[1],[2],[3],[4]])

y=np.array([[12],[19],[29],[37],[45]])

In [4]:
LR = LinearRegression()

In [5]:
LR.fit(X, y)

LinearRegression()

In [6]:
LR.coef_

array([[8.4]])

In [7]:
LR.intercept_

array([11.6])

In [8]:
from sklearn.preprocessing import PolynomialFeatures

In [9]:
x = np.array([[2,3]])

In [17]:
poly_conv = PolynomialFeatures(degree=3, include_bias=True)

In [18]:
X_poly = poly_conv.fit_transform(x)

In [19]:
X_poly

array([[ 1.,  2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.]])

In [22]:
x2 = np.array([[2], [3], [4]])

In [23]:
poly2 = PolynomialFeatures(degree=3, include_bias=True)

In [24]:
xp2 = poly2.fit_transform(x2)

In [25]:
xp2

array([[ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.],
       [ 1.,  4., 16., 64.]])

In [26]:
x3 = np.array([[0,2],[4,5],[7,8]])

In [27]:
poly3 = PolynomialFeatures(degree=3, include_bias=True)

In [28]:
xp3 = poly3.fit_transform(x3)

In [29]:
xp3

array([[  1.,   0.,   2.,   0.,   0.,   4.,   0.,   0.,   0.,   8.],
       [  1.,   4.,   5.,  16.,  20.,  25.,  64.,  80., 100., 125.],
       [  1.,   7.,   8.,  49.,  56.,  64., 343., 392., 448., 512.]])