<img src="https://drive.google.com/uc?export=view&id=1Y-EIpLOigI9ycCOZRrRSFzAfuN9cxhqT" alt="Hobot Academy" width="300" height="300">

<h1 align="center"><font size="14">Hands-On Machine Learning</font></h1>
<h3 align="center"><font size="7">Session07: Linear Regression</font></h3>
<h3 align="center">Zahra Amini</h3>

In [1]:
import numpy as np

In [2]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([[460], [232], [178]])

In [3]:
X_train

array([[2104,    5,    1,   45],
       [1416,    3,    2,   40],
       [ 852,    2,    1,   35]])

In [4]:
y_train

array([[460],
       [232],
       [178]])

In [5]:
print("X_train_shape: ", X_train.shape, "\n\ny_train_shape: ", y_train.shape)

X_train_shape:  (3, 4) 

y_train_shape:  (3, 1)


# With For

In [6]:
b_init = 785
w_init = np.array([ 0.3, 18.5, -53.3, -26.4])

In [7]:
w_init.shape

(4,)

In [8]:
m = X_train.shape[0]

n= X_train.shape[1]

In [11]:
y_pred = np.zeros((m,1))

for i in range(m):
    p =0
    for j in range(n):
        p += X_train[i][j] * w_init[j]
    y_pred[i] = p+b_init

In [15]:
y_pred

array([[267.4],
       [102.7],
       [100.3]])

In [16]:
y_pred.shape

(3, 1)

# Vectorization

In [13]:
y_p = np.dot(X_train, w_init) + b_init

In [14]:
y_p

array([267.4, 102.7, 100.3])

In [17]:
y_p.shape

(3,)

In [19]:
(y_p).shape

(3,)

In [21]:
(X_train.T).shape

(4, 3)